ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: ecommerce_db
      schema: dev
      threads: 4